eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true 

#used for set value
user:
  role: Admin

welcome:
  message: Welcome to the Spring Cloud Config managed application!
